### ISSUE TITLE
Build wheel mmcv failed in Linux Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by andrearafanelli** [Luodian/RelateAnything#9]
It failed to install into my server

```
 ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1516, in _run_ninja_build
          subprocess.run(
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ag265vjf/mmcv_048b0b8fb4b64d62aa0c96422d7e11cc/setup.py", line 437, in <module>
          setup(
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
          build_ext.build_extensions(self)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 473, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/arafanelli/miniconda3/envs/relate_anything/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects

```

**Comment by andrearafanelli** [comment]
Check my fork : https://github.com/andrearafanelli/RelateAnything 
where I downgraded to mmcv-lite
